---
# Usage:
#   ansible-playbook -i tropicana, update-odroid-c2.yaml -K

- name: Update Odroid C2 to latest
  hosts: all
  gather_facts: false
  become: true

  vars:
    squid_proxy_host: squid02.stillwell
    squid_proxy_port: 3128

  tasks:
    - name: Configure APT to use local Squid proxy
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/90aptproxy
        content: |
          Acquire::http::Proxy "http://{{ squid_proxy_host }}:{{ squid_proxy_port }}/";
          Acquire::https::Proxy "DIRECT";
        mode: "0644"
        backup: yes

    - name: Stop and disable ramlog service
      ansible.builtin.service:
        name: armbian-ramlog
        state: stopped
        enabled: no

    - name: Stop and disable zram-config service
      ansible.builtin.service:
        name: armbian-zram-config
        state: stopped
        enabled: no

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 0
      changed_when: false

    - name: Perform full-upgrade
      ansible.builtin.apt:
        upgrade: full
        autoremove: yes
        autoclean: yes

    - name: Install a selection of packages
      ansible.builtin.apt:
        name: btop
        state: latest

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Rebooting system by Ansible after a full-upgrade"
        reboot_timeout: "300"
        connect_timeout: 30
        delay: 10
        pre_reboot_delay: 15
      when:
        - reboot_required.stat.exists

    - name: Summary of what was upgraded
      ansible.builtin.debug:
        msg: |
          {{ apt_upgrade.upgrade_summary | default('No packages were upgraded') }}
